services:
  - type: web
    name: ultravox-stream-server
    runtime: python
    buildCommand: pip install -r requirements.txt && chmod +x run.sh
    startCommand: ./run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
